import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  creator:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdG9yIjoiTXVoYW1tYWQgUmFkaWFuIFJhc3lpZCIsImdpdGh1YiI6Imh0dHBzOi8vZ2l0aHViLmNvbS9yYWRpYW5yYXN5aWQiLCJsaW5rZWRpbiI6Imh0dHBzOi8vd3d3LmxpbmtlZGluLmNvbS9pbi9tdWhhbW1hZHJhZGlhbnJhc3lpZC8ifQ.BU4EgjOiq5rcG5NPFshcQBYNCX2t8rWEdNrAeJ0KDvI",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
